### PR TITLE
Timer component completed code.

### PR DESCRIPTION
**Pull request by ChrisMunozCodes**
This code completes the timer functionality which includes:

- User can input the amount of minutes they wish the the timer to start at and the timer will format their time into 0:00:00 format and start counting down.
- Pause / Resume time feature.
- Timer reset feature.

### CODE REVIEW

**Review by adan-ayaz-stan — CHANGES_REQUESTED** [review]
There are '<<<<<<' , '=======' , '>>>>>>' in the code.

**Review by adan-ayaz-stan — COMMENTED** [review]
The code is a little buggy but Jersey Devil can decide if it's going to be merged.

In my opinion tho, Chris could try to resolve the issue by himself. There's more learning through one's own trial and error. It'll stay in mind the next time something like this comes up.

If he's successful, we can review and merge it.
If not, Chris could always ask for help. I'd be glad to volunteer.

**Review by djneill — CHANGES_REQUESTED** [review]
Exceptional work, I'm impressed. It appears that the timer is running a bit fast, and I believe making a slight adjustment would ensure the best possible outcome.

**Comment by ChrisMunozCodes** [comment]
I updated the branch to reflect the changes for the code that should resolve the bugs as well as add additional features where buttons are disabled / enabled during certain actions.

Please review and let me know if any further issues persist, thank you!

**Pull request closed without merging**
